apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  config.json: |
    {
      "API_URL": "http://a1e8d4594c6c743cba23a59ebdd308dd-1836304983.eu-central-2.elb.amazonaws.com/"
    }
    