name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - 'api/**'

jobs:
  # Continuous Integration job
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the backend image
    - name: Build backend image
      run: |
        docker build -f api/Dockerfile -t alexandrebo/3-tier-application-backend:latest ./api

    # Build the frontend image
    - name: Build frontend image
      run: |
        docker build -f ui/Dockerfile -t alexandrebo/3-tier-application-frontend:latest ./ui

    # Push the images to DockerHub
    - name: Push backend image to DockerHub
      run: |
        docker push alexandrebo/3-tier-application-backend:latest

    - name: Push frontend image to DockerHub
      run: |
        docker push alexandrebo/3-tier-application-frontend:latest

  # Continuous Delivery job
  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Update kubeconfig and deploy to EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
    
    - name: Check kubectl version
      run: kubectl version --client 

    - name: Deploy to EKS
      run: |
        kubectl apply -f ./kubernetes/backend-deployment-service.yaml
        kubectl apply -f ./kubernetes/database-deployment-service.yaml
        kubectl apply -f ./kubernetes/frontend-configmap.yaml
        kubectl apply -f ./kubernetes/frontend-deployment-service.yaml